/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-primary": "#ffffff",
          "secondary-container": "#dfdfe7",
          "on-tertiary-container": "#ffb3a7",
          "on-secondary-fixed": "#191b21",
          "outline-variant": "#c2c6d3",
          "inverse-surface": "#2f3132",
          "outline": "#727782",
          "tertiary-fixed": "#ffdad4",
          "error": "#ba1a1a",
          "secondary": "#5c5e65",
          "surface-container-lowest": "#ffffff",
          "tertiary-fixed-dim": "#ffb4a8",
          "on-secondary": "#ffffff",
          "on-error": "#ffffff",
          "on-primary-fixed": "#001c3b",
          "surface-container-highest": "#e2e2e4",
          "surface-container-low": "#f3f3f5",
          "ink-black": "#22242A",
          "primary-fixed-dim": "#a6c8ff",
          "sale-red": "#CD0000",
          "surface-container-high": "#e8e8ea",
          "surface-tint": "#1d5fa8",
          "surface-bright": "#f9f9fb",
          "on-background": "#1a1c1d",
          "on-surface": "#1a1c1d",
          "on-secondary-fixed-variant": "#45464d",
          "surface-container": "#eeeef0",
          "tertiary-container": "#a90000",
          "on-primary-container": "#a5c7ff",
          "on-error-container": "#93000a",
          "secondary-fixed-dim": "#c5c6ce",
          "inverse-primary": "#a6c8ff",
          "error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#930000",
          "on-tertiary-fixed": "#410000",
          "on-secondary-container": "#616269",
          "tertiary": "#7d0000",
          "primary-container": "#00529b",
          "surface-gray": "#F4F4F6",
          "background": "#f9f9fb",
          "surface-dim": "#d9dadc",
          "inverse-on-surface": "#f0f0f2",
          "on-tertiary": "#ffffff",
          "surface": "#f9f9fb",
          "on-primary-fixed-variant": "#004787",
          "secondary-fixed": "#e2e2ea",
          "primary": "#003b72",
          "surface-variant": "#e2e2e4",
          "border-subtle": "#E5E7EB",
          "primary-fixed": "#d5e3ff",
          "on-surface-variant": "#424751"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "grid-margin-desktop": "48px",
          "card-padding": "12px",
          "gutter": "16px",
          "base": "4px",
          "grid-margin-mobile": "16px",
          "section-gap": "64px"
      },
      "fontFamily": {
          "headline-lg-mobile": ["Libre Franklin"],
          "body-lg": ["Inter"],
          "headline-md": ["Libre Franklin"],
          "label-caps": ["Inter"],
          "display-lg": ["Libre Franklin"],
          "price-lg": ["Inter"],
          "headline-lg": ["Libre Franklin"],
          "price-sm": ["Inter"],
          "body-md": ["Inter"]
      },
      "fontSize": {
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
          "display-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "price-lg": ["20px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
          "price-sm": ["14px", { "lineHeight": "18px", "fontWeight": "600" }],
          "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
